{{- if .Values.global.podSecurityPolicy.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "approver.fullname" . }}-psp
  labels:
    app: {{ include "approver.name" . }}
    app.kubernetes.io/name: {{ include "approver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "approver"
    helm.sh/chart: {{ include "approver.chart" . }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "approver.fullname" . }}
{{- end }}
